server:
  tomcat:
    uri-encoding: utf-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /emos-wx-api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 8
      max-active: 16
      min-idle: 8
      max-wait: 60000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: localhost
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emos
      authentication-database: admin
      username: root
      password: root
  mail:
    default-encoding: UTF-8
    host: smtp.aliyun.com
    username: zhaihonghao317@aliyun.com
    password: Zhh980317

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.example.emos.wx.db.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    root: info
    com.example.emos.wx.db.dao: warn
  pattern:
    console: "%d{HH:mm:ss}  %-5level  %msg%n"

emos:
  jwt:
    #密钥
    secret: abc123456
    #令牌过期时间（天）
    expire: 5
    #令牌缓存时间（天）
    cache-expire: 10
  face:
    createFaceModelUrl: http://10.15.22.182:3000/create_face_model
    checkinUrl: http://10.15.22.182:3000/checkin
  email:
    system: zhaihonghao317@aliyun.com
    hr: 1095971161@qq.com
  image-folder: D:/others/emos/image
  code: 12341

wx:
  app-id: wxab64ef0b75837fe8
  app-secret: 
